// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA05nLLeyqNCxaFGLb_KVWErNfHkQHwXWE',
    appId: '1:1057944444907:web:bcb7587050f96f5fca03ae',
    messagingSenderId: '1057944444907',
    projectId: 'temphumid-6e7fb',
    authDomain: 'temphumid-6e7fb.firebaseapp.com',
    storageBucket: 'temphumid-6e7fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD39Ror8AyhA7Y_drWo1sX2cQZdIHlJV8w',
    appId: '1:1057944444907:android:ffd18888e7dec1a0ca03ae',
    messagingSenderId: '1057944444907',
    projectId: 'temphumid-6e7fb',
    storageBucket: 'temphumid-6e7fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKxAq5Q71C0z7nxjjPIwba6IvyYX0CbfE',
    appId: '1:1057944444907:ios:4e0ec90a139758e6ca03ae',
    messagingSenderId: '1057944444907',
    projectId: 'temphumid-6e7fb',
    storageBucket: 'temphumid-6e7fb.firebasestorage.app',
    iosBundleId: 'com.example.esp32TempHumid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKxAq5Q71C0z7nxjjPIwba6IvyYX0CbfE',
    appId: '1:1057944444907:ios:4e0ec90a139758e6ca03ae',
    messagingSenderId: '1057944444907',
    projectId: 'temphumid-6e7fb',
    storageBucket: 'temphumid-6e7fb.firebasestorage.app',
    iosBundleId: 'com.example.esp32TempHumid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA05nLLeyqNCxaFGLb_KVWErNfHkQHwXWE',
    appId: '1:1057944444907:web:078e6ae7261a6d64ca03ae',
    messagingSenderId: '1057944444907',
    projectId: 'temphumid-6e7fb',
    authDomain: 'temphumid-6e7fb.firebaseapp.com',
    storageBucket: 'temphumid-6e7fb.firebasestorage.app',
  );
}
